syntax = "proto2";
package org.minbase.common.rpc.proto.generated;

message ColumnValue {
  required bytes column = 1;
  required bytes tableValue = 2;
}

message GetRequest {
  required bytes key = 1;
  required bytes table = 2;
  repeated bytes columns = 3;
}

message GetResponse {
  required bytes key = 1;
  required int32 statusCode = 2;
  repeated ColumnValue columnValues = 3;
}

message PutRequest {
  required bytes key = 1;
  required bytes table = 2;
  repeated ColumnValue columnValues = 3;
}

message PutResponse {
  required int32 statusCode = 1;
}

message CheckAndPutRequest {
  required bytes checkKey = 1;
  required bytes checkColumn = 2;
  required bytes checkValue = 3;
  required bytes key = 4;
  required bytes table = 5;
  repeated ColumnValue columnValues = 6;
}

message CheckAndPutResponse {
  required int32 statusCode = 1;
}

message DeleteRequest {
  required bytes key = 1;
  required bytes table = 2;
  repeated bytes columns = 3;
}

message DeleteResponse {
  required int32 statusCode = 1;
}

message BeginTransactionRequest {

}

message BeginTransactionResponse {
  required int32 statusCode = 1;
  required int64 txid = 2;
}

message RollBackRequest {
  required int64 txid = 1;
}

message RollBackResponse {
  required int32 statusCode = 1;
}

message CommitRequest {
  required int64 txid = 1;
}

message CommitResponse {
  required int32 statusCode = 1;
}

message ScanRequest {
  required bytes table = 1;
  required bytes startKey = 2;
  required bytes endKey = 3;
  required int32 rowCountLimit = 4;
}

message Row {
  required bytes rowKey = 1;
  repeated ColumnValue columnValues = 2;
}

message ScanResponse {
  required int32 statusCode = 1;
  repeated Row rows = 2;
}

service ClientService {
  rpc get(GetRequest) returns (GetResponse);
  rpc put(PutRequest) returns (PutResponse);
  rpc checkAndPut(CheckAndPutRequest) returns (CheckAndPutResponse);
  rpc delete(DeleteRequest) returns (DeleteResponse);
  rpc scan(ScanRequest) returns (ScanResponse);
  rpc beginTransaction(BeginTransactionRequest) returns (BeginTransactionResponse);
  rpc rollBack(RollBackRequest) returns (RollBackResponse);
  rpc commit(CommitRequest) returns (CommitResponse);
}


message TxGetRequest {
  required int64 txid = 1;
  required bytes key = 2;
  required bytes table = 3;
  repeated bytes columns = 4;
}

message TxGetResponse {
  required bytes key = 1;
  required int32 statusCode = 2;
  repeated ColumnValue columnValues = 3;
}

message TxPutRequest {
  required int64 txid = 1;
  required bytes key = 3;
  required bytes table = 4;
  repeated ColumnValue columnValues = 5;
}

message TxPutResponse {
  required int32 statusCode = 1;
}

message TxCheckAndPutRequest {
  required int64 txid = 1;
  required bytes checkKey = 2;
  required bytes checkColumn = 3;
  required bytes checkValue = 4;
  required bytes key = 5;
  required bytes table = 6;
  repeated ColumnValue columnValues = 7;
}

message TxCheckAndPutResponse {
  required int32 statusCode = 1;
}

message TxDeleteRequest {
  required int64 txid = 1;
  required bytes key = 2;
  required bytes table = 3;
  repeated bytes columns = 4;
}

message TxDeleteResponse {
  required int32 statusCode = 1;
}

service TransactionService {
  rpc get(TxGetRequest) returns (TxGetResponse);
  rpc put(TxPutRequest) returns (TxPutResponse);
  rpc checkAndPut(TxCheckAndPutRequest) returns (TxCheckAndPutResponse);
  rpc delete(TxDeleteRequest) returns (TxDeleteResponse);
}


